#!/usr/bin/env python
from transformers import Trainer
import torch

##
DEF_K = 5
##

class FirstCharTrainer(Trainer):
    
    def compute_loss(self, model, inputs, return_outputs: bool = False, num_items_in_batch = None):
        #Actively ignores incomplete token (tokens with no complete character) and tokens starting with space
        #Checks the top 5 logits ON THE GRADED LABEL then check if any "has the same starting character"
        #    if so, RE-LABEL the corresponding label to the one such as above that scores the highest
        #    => I've effectively simulated/approximated "multiple correct labels" with relatively small cost
        if not "AVeryUnwieldyNameUsedForSpecificPurpose" in dir(self):
            assert False, "FirstCharTrainer is not properly initialized."
        
        id_to_fc = self.AVeryUnwieldyNameUsedForSpecificPurpose
        outputs = model(**inputs)
        
        mvals, minds = torch.max(inputs["labels"], dim=-1) #pick the only non- "-100" token
            #<batch size>-long list of <dict-size> pytorch vectors
        
        for i in range(len(outputs.logits)): #ith example in batch
            if mvals[i] < 0:
                continue #invalid example generated by DC (very rare)
            c_char = id_to_fc[int(mvals[i])]
            if c_char in [" ", "\ufffd"]: #ignore spaces + incomplete characters
                continue
            
            L = outputs.logits[i, minds[i]] #relevant logit at ith example
            _, top5_logits_ind = torch.topk(L, k=5, sorted=True) #look at top 5 logits
            for j in range(5):
                if c_char == id_to_fc[top5_logits_ind[j].item()]:
                    #replace the label to this one! (i.e. greedy-reward model for guessing the correct character)
                    inputs["labels"][i][minds[i]] = top5_logits_ind[j]
                    break
            
        
        
        loss, outputs = super().compute_loss(model, inputs, True, num_items_in_batch)
        return (loss, outputs) if return_outputs else loss
